# Generated by Django 4.2.11 on 2024-07-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0002_group_text_module_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_cards', to='learneasy.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='model_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_modules', to='learneasy.group'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_texts', to='learneasy.group'),
        ),
    ]
