# Generated by Django 4.2.11 on 2024-07-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0003_alter_card_card_module_alter_module_model_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='model_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_modules', to='learneasy.group'),
        ),
    ]
