# Generated by Django 4.2.11 on 2024-07-07 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('group_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_name', models.CharField(max_length=64)),
                ('text_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_groups', to='learneasy.group')),
                ('text_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_texts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=64)),
                ('model_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_groups', to='learneasy.group')),
                ('module_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=48)),
                ('definition', models.CharField(max_length=128)),
                ('card_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_module', to='learneasy.module')),
            ],
        ),
    ]
