# Generated by Django 4.2.11 on 2024-07-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0004_alter_module_model_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='model_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_modules', to='learneasy.group'),
        ),
    ]
