# Generated by Django 4.2.11 on 2024-07-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0005_alter_module_model_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_content',
            field=models.TextField(default='exaple text', max_length=8096),
            preserve_default=False,
        ),
    ]
