# Generated by Django 5.0.3 on 2024-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0008_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='english', max_length=24),
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
    ]
