# Generated by Django 5.0.3 on 2024-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learneasy', '0010_group_group_emoji_module_module_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=24),
        ),
    ]
